/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin. 
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2024-06-11 11:19:31
 */
package y5u1.cosmic.debug;

import kd.cosmic.debug.tools.CosmicLauncher;

/**
 * 启动本地应用程序(微服务节点)
 */
public class DebugApplication {
	
	

    public static void main(String[] args) {
    	
//    	Thread.currentThread().setContextClassLoader(new KDSecurityClassLoader(Thread.currentThread().getContextClassLoader()));
    	
        CosmicLauncher cosmic = new CosmicLauncher(false);

        cosmic.setClusterNumber("cosmic");
        cosmic.setTenantNumber("ierp");
//        cosmic.setConfigUrl("127.0.0.1:2181?user=zk&password=123456");
        cosmic.setConfigUrl("127.0.0.1:2181","zookeeper","miaosu5limi");
//        cosmic.setConfigUrl("127.0.0.1:2181");
//        cosmic.setMcServerUrl("http://127.0.0.1:8090");
        cosmic.setMcServerUrl("https://127.0.0.1:9080"); 

//        cosmic.setWebResPath("D:/StarrySkyFlagshipEdition/environment/static-file-service");
        
//        cosmic.setFsServerUrl("127.0.0.1", 8100);
//        cosmic.setImageServerUrl("127.0.0.1", 8100);
        
        //自定义本地苍穹调试服务的端口
        cosmic.setCosmicWepPort(8881);
        cosmic.set("lightweightdeploy", "true");  //标注环境为轻量级
        cosmic.set("redismodelcache.enablelua", "false");  //轻量级不能用lua，设为false
        cosmic.set("lightweightdeploy.services" , "");  //设置服务为空。服务由MC启动，这里就不用启动了。
//        cosmic.setDubboConfig(false, true, true);
        cosmic.start();
        
        
    }
}